version: 0.1
loglevel: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
tls:
  certificate: /etc/docker/certs.d/10.129.0.34:5000/cert.pem
  key: /etc/docker/certs.d/10.129.0.34:5000/key.pem
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3