services:

#------------------------------------

  postgres:
    image: postgres
    container_name: my-postgres-2025
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer4617
    ports:
      - 4032:5432
    volumes:
      - ./backend/app/config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - my-pg-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

#------------------------------------

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-2025
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers.json
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 4080:80
    volumes:
      - ./backend/scripts/pg-admin-scripts/servers.json:/var/lib/pgadmin/servers.json
      - my-pg-admin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

#------------------------------------

  backend:
    build: ./backend/lyalya
    container_name: backend-deploy 
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

#------------------------------------

  frontend:
    build: ./frontend
    container_name: frontend-deploy 
    ports:
      - 4488:4488

#------------------------------------

volumes:
  my-pg-volume: {}
  my-pg-admin: {}
  backend-deploy:
  frontend-deploy:
  # grafana-storage: {}
  # prometheus-data: {}