FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /backend

ENV PYTHONUNBUFFERED=1

COPY ./backend/lyalya/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py makemigrations --settings=lyalya.settings_test && python manage.py migrate --settings=lyalya.settings_test

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8001 --settings=lyalya.settings_test"]