global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
  
  # # Прописать свои метрики и подключить
  # - job_name: python_service
  #   static_configs:
  #     - targets: ['python-container:8080']