name: Checking and publishing the project (CI-CD)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Check Docker Compose Syntax
        run: sudo docker compose config
      - name: Creating a swarm docker
        run: sudo docker swarm init
      # - name: We are checking the possibility of assembling containers
      #   run: sudo docker compose up --build -d
      # - name: Stop and delete the previous version
      #   run: sudo docker compose down -v
      - name: Building a new version
        run: sudo docker compose build
      - name: Deploy repository
        run: sudo docker stack deploy --compose-file docker-compose.yml myapp
      - name: Stopping and deleting the compiled application
        run: sudo docker stack rm myapp
      - name: Cleaning up unused images
        run: sudo docker system prune -f # -f пропуск вопроса [y/N] (можно -af тогда ВСЕ лишнее удалим) 
  test:
    needs: [build]
    runs-on: self-hosted # ubuntu-latest, если на серверах GitHub; self-hosted, если свой сервер
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Установка актуальной версии Python
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libpq-dev sqlite3 && pip install -r ./backend/lyalya/requirements.txt
      - name: Migrate testDB
        run: python ./backend/lyalya/manage.py makemigrations --settings=lyalya.settings_test && python ./backend/lyalya/manage.py migrate --settings=lyalya.settings_test 
      - name: Run Tests Models
        run: python ./backend/lyalya/manage.py test core.tests.models --settings=lyalya.settings_test
      - name: Run Tests API View
        run: python ./backend/lyalya/manage.py test core.tests.api_view --settings=lyalya.settings_test
      - name: Run Tests HTML View
        run: python ./backend/lyalya/manage.py test core.tests.html_view --settings=lyalya.settings_test
  deploy:
    needs: [build, test]
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cleaning up unused images
        run: sudo docker system prune -f # -f пропуск вопроса [y/N] (можно -af тогда ВСЕ лишнее удалим)
      - name: Building a new version
        run: sudo docker compose build
      - name: Deploy repository
        run: sudo docker stack deploy --compose-file docker-compose.yml myapp